### ISSUE TITLE
Generator throws type error: undefined is not a function line 149 of Generator.js

### ISSUE THREAD

**Issue by mrpetef10** [irlnathan/sails-generate-scaffold#13]
Please review the below log after a successful installation:

C:\wamp\www\Sails Projects\sails-hybrid>npm install sails-generate-scaffold
sails-generate-scaffold@0.0.5 node_modules\sails-generate-scaffold
+-- underscore.string@2.4.0
+-- merge-defaults@0.2.1 (lodash@2.4.1)
+-- lodash@3.5.0

C:\wamp\www\Sails Projects\sails-hybrid>sails generate scaffold user name:string
 age:integer email:email
C:\wamp\www\Sails Projects\sails-hybrid\node_modules\sails-generate-scaffold\Gen
erator.js:149
    compiledNewFlash = compiledNewFlash.replace(/ERBstart/g, '<%')
                                        ^
TypeError: undefined is not a function
    at Object.module.exports.before (C:\wamp\www\Sails Projects\sails-hybrid\nod
e_modules\sails-generate-scaffold\Generator.js:149:41)
    at generate (C:\Users\admin\AppData\Roaming\npm\node_modules\sails\node_modu
les\sails-generate\lib\generate.js:73:13)
    at module.exports (C:\Users\admin\AppData\Roaming\npm\node_modules\sails\nod
e_modules\sails-generate\lib\index.js:112:3)
    at Command.module.exports (C:\Users\admin\AppData\Roaming\npm\node_modules\s
ails\bin\sails-generate.js:104:10)
    at Command.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\sail
s\node_modules\commander\index.js:249:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (C:\Users\admin\AppData\Roaming\npm\node_modules\sails\
node_modules\commander\index.js:477:12)
    at Command.parse (C:\Users\admin\AppData\Roaming\npm\node_modules\sails\node
_modules\commander\index.js:370:21)
    at Object.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\sails
\bin\sails.js:158:9)
    at Module._compile (module.js:460:26)

C:\wamp\www\Sails Projects\sails-hybrid>

**Comment by vinithmt** [comment]
I am getting the same issue. Please help me out.

/var/www/foo/node_modules/sails-generate-scaffold/Generator.js:149
    compiledNewFlash = compiledNewFlash.replace(/ERBstart/g, '<%')
                                        ^
TypeError: Object function (obj) {
obj || (obj = {});
var __t, __p = '';
with (obj) {
__p += 'ERBstart if(flash && flash.err) { ERBend\n<ul class="alert alert-success">\nERBstart Object.keys(flash.err).forEach(function(error) { ERBend\n<li><%- JSON.stringify(flash.err[error]) ERBend</li>\nERBstart }) ERBend\n</ul>\nERBstart } ERBend';

}
return __p
} has no method 'replace'
    at Object.module.exports.before (/var/www/foo/node_modules/sails-generate-scaffold/Generator.js:149:41)
    at generate (/usr/lib/node_modules/sails/node_modules/sails-generate/lib/generate.js:73:13)
    at module.exports (/usr/lib/node_modules/sails/node_modules/sails-generate/lib/index.js:112:3)
    at Command.module.exports (/usr/lib/node_modules/sails/bin/sails-generate.js:104:10)
    at Command.<anonymous> (/usr/lib/node_modules/sails/node_modules/commander/index.js:249:8)
    at Command.emit (events.js:98:17)
    at Command.parseArgs (/usr/lib/node_modules/sails/node_modules/commander/index.js:477:12)
    at Command.parse (/usr/lib/node_modules/sails/node_modules/commander/index.js:370:21)
    at Object.<anonymous> (/usr/lib/node_modules/sails/bin/sails.js:158:9)
    at Module._compile (module.js:456:26)

**Comment by tcury** [comment]
I got the same problem.

**Comment by stefan1968** [comment]
Me too.

**Comment by cactis** [comment]
me too.

**Comment by maczor** [comment]
same here sails 0.11.0

**Comment by ogrotten** [comment]
I'll just go ahead and pile on here with another "me too in sails 0.11.0"

Disappointing.

**Comment by erikmellum** [comment]
Yep me too.

**Comment by BipinBhandari** [comment]
Me too

**Comment by Ozhvankov** [comment]
;( me too. I got the same problem  in sails v0.11.0. 
that about "recipe"? any one ?

**Comment by mak4alex** [comment]
me too

**Comment by Ozhvankov** [comment]
ok I fink all triable on /node_modules/sails_generate_../Generator.js 
149| compiledNewFlash = compiledNewFlash.replace(/ERBstart/g, '<%')   and so on 
 i fink structure of code not right maybe need : (value, searchFor, replaceWith) ->
  value.toString().replace(searchFor, replaceWith)
want to start patching  in next Monday .
need an alternative point of view !
That U fink Guys ?

**Comment by dlmoody** [comment]
I have fixed this issue. I guess I should make a PR

**Comment by dlmoody** [comment]
@irlnathan Ok I fixed this issue, let me know if you want me to create a PR

**Comment by stefan1968** [comment]
Yes please.

**Comment by cubico** [comment]
Hi guys, the issue is on _.template calling. First we must create the compiled template, and then bind the parameters. Search all _.template code and replace by the fix as the following example:

Lines similar to: 

``` javascript
142) var compiledNewFlash = _.template(NEW_FLASH_TEMPLATE,{
```

are replaced by:

``` javascript
142) var compiledNewFlash = _.template(NEW_FLASH_TEMPLATE)({
```

**Comment by mansoorriaaz** [comment]
Any solution for this issuses?? the module hasn't been fixed and i am still facing the same problem. any help would be great.thx

**Comment by thiagozs** [comment]
+1

**Comment by marlonscalabrin** [comment]
See https://github.com/irlnathan/sails-generate-scaffold/issues/15#issuecomment-221659493

**Comment by atularvind** [comment]
Thanks @marlonscalabrin it resolves the issue.
